cache:
  - apt
  - pip
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
  - secure: QBB2KT4EFUdSkH9fjo5J/02zuZlD0FbVsKwYJgW6c4INp1UY/nx0nrsgjPSZQMD2HBztdfEZInugoVrOJwXBzWJ5Ioc19T9oYhnzaIF6oJRo1mTYDhragvdwiLfb0AyylGq7bgP4lgoMBtE1Oxauf0rKVEYiVeEhvHJup/di6A4=
  matrix:
  - LLVM_VERSION=3.5
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - PY_MAJOR_MINOR=${TRAVIS_PYTHON_VERSION:0:3}
  # Setup environment
  - conda create -n travisci --yes python=$PY_MAJOR_MINOR
  - source activate travisci
  - conda install --yes -c numba llvmdev
  - conda install --yes numpy pip matplotlib
  - if [ $PY_MAJOR_MINOR \< "3.4" ]; then conda install --yes enum34; fi
  # We need this line to have g++ 4.8 available in apt
  # (Travis' default gcc version doesn't support C++11).
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8 fglrx=2:8.960-0ubuntu1 opencl-headers
  # Force g++ 4.8 to be the default version
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

install:
  - export PYTHON_VERSION=$(python -c 'import sys; print(sys.version_info[0:2])')
  - pip install coveralls coverage setuptools nose pygments pycl
  - if [ $PY_MAJOR_MINOR \< "3.0" ]; then pip install opentuner; fi
  - pip install -e git://github.com/leonardt/llvmlite.git#egg=llvmlite
  - nosetests --version
  - coverage --version
  - python setup.py install
script:
  - cd ${TRAVIS_BUILD_DIR}
  - nosetests --verbose --with-coverage --cover-package=ctree --cover-min-percentage=90
    --cover-erase
notifications:
  slack: ucb-sejits:cPZxBunxagWZ763mcsIXOV0W
deploy:
  provider: pypi
  user: leonardt
  password:
    secure: SMiyQflUvfG0M8bR07Sri8VXnPSFKprNxA3RF7sljk99Aj9BuuuBRLkcOhkYtIRYfgHUSEnFeYYe+rb8y6BV/LnulCQiw9bCIqmPY9IYGy63DNjUGxh65MyO9HDjwz4hi+4endwZTXaUL3X4de9Xk3NnDhHISiLd7WymR9YQ7eE=
  on:
    tags: true
    all_branches: true
    repo: ucb-sejits/ctree
